services:
  nginx:
    image: nginx:alpine
    container_name: engsoft-frontend
    env_file:
      - .env
    ports:
      - "80:80" # HTTP traffic (is optional if you want to redirect to HTTPS)
      - "443:443" # HTTPS traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
      - ${PUBLIC_CERTIFICATE_PATH}:/etc/ssl/certs/ssl-cert-snakeoil.pem # Public https certificate
      - ${PRIVATE_CERTIFICATE_PATH}:/etc/ssl/private/ssl-cert-snakeoil.key # Private https key
